{{- if and .Values.openshift.enabled .Values.openshift.routes.enabled .Values.openshift.routes.api.enabled .Values.foundationalFlywheelServer.deployments.api.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.foundationalFlywheelServer.deployments.api.fullnameOverride }}-route
  labels:
    app: {{ .Values.foundationalFlywheelServer.deployments.api.fullnameOverride }}-deployment
spec:
  {{- if .Values.openshift.routes.api.host }}
  host: {{ .Values.openshift.routes.api.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.foundationalFlywheelServer.deployments.api.fullnameOverride }}-service
    weight: 100
  port:
    targetPort: {{ .Values.foundationalFlywheelServer.deployments.api.service.port }}
  {{- if .Values.openshift.routes.api.tls.enabled }}
  tls:
    termination: {{ .Values.openshift.routes.api.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.openshift.routes.api.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
