{{- if .Values.secrets.ngcApiKey }}
{{- $root := . }}
{{- range .Values.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $root.Values.namespace }}
  labels:
    {{- include "data-flywheel-blueprint-helm-chart.labels" $root | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": delete
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .registry .username $root.Values.secrets.ngcApiKey (printf "%s:%s" .username $root.Values.secrets.ngcApiKey | b64enc) | b64enc | quote }}
{{- end }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ngcApiSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "data-flywheel-blueprint-helm-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": delete
type: Opaque
data:
  NGC_API_KEY: {{ if .Values.secrets.ngcApiKey }}{{ .Values.secrets.ngcApiKey | b64enc }}{{ else }}{{ "" | b64enc }}{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nvidiaApiSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "data-flywheel-blueprint-helm-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": delete
type: Opaque
data:
  NVIDIA_API_KEY: {{ if .Values.secrets.nvidiaApiKey }}{{ .Values.secrets.nvidiaApiKey | b64enc }}{{ else }}{{ "" | b64enc }}{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hfSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "data-flywheel-blueprint-helm-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": delete
type: Opaque
data:
  HF_TOKEN: {{ if .Values.secrets.hfToken }}{{ .Values.secrets.hfToken | b64enc }}{{ else }}{{ "" | b64enc }}{{ end }}

{{- if .Values.secrets.llmJudgeApiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.llmJudgeSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "data-flywheel-blueprint-helm-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": delete
type: Opaque
data:
  LLM_JUDGE_API_KEY: {{ .Values.secrets.llmJudgeApiKey | b64enc }}
{{- end }}

{{- if .Values.secrets.embApiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.embSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "data-flywheel-blueprint-helm-chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": delete
type: Opaque
data:
  EMB_API_KEY: {{ .Values.secrets.embApiKey | b64enc }}
{{- end }}
