apiVersion: v2
name: nvidia-blueprint-data-flywheel
description: A Helm chart for Data Flywheel Blueprint
dependencies:
- name: nemo-microservices-helm-chart
  condition: nemo-microservices-helm-chart.enabled
  repository: https://helm.ngc.nvidia.com/nvidia/nemo-microservices
  version: '25.8.0'
type: application
version: "0.3.1"
appVersion: "0.3.1"
